linters-settings:
  dupl:
    threshold: 100
  errorlint:
    errorf: true
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
    govet:
      check-shadowing: true
    goconst:
      min-len: 2
      min-occurrences: 2
    # gocritic:
    #   enabled-tags:
    #     - diagnostic
    #     - experimental
    #     - opinionated
    #     - performance
    #     - style
    disabled-checks:
      - dupImport
      - unnecessaryBlock
  # gofumpt:
  #   extra-rules: true
  # gomnd:
  #   settings:
  #     mnd:
  #       checks:
  #         - argument
  #         - case
  #         - condition
  #         - operation
  #         - return
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    # - gocritics
    - gocyclo
    # - godot
    # - godox
    - gofmt
    # - gofumpt
    - goimports
    # - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - paralleltest
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

# disable:
#    - exhaustivestruct
#    - ifshort
#    - goheader
#    - prealloc
#    - testpackage
#    - wrapcheck

run:
  deadline: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - internal/generated
  skip-files:
    - ".*\\_test\\.go$"
