version: "3.9"
services:
  postgresdb:
    container_name: postgres
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    container_name: app
    image: app
    restart: on-failure
    build: .
    env_file: .env
    environment:
      POSTGRES_HOST: postgresdb
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

volumes:
  postgres:
